package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import com.codeborne.selenide.Condition;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selectors.byText;
import static com.codeborne.selenide.Selenide.*;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class IBSTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("IBS-tests")
    void ibsTest() {
        step("Open url 'https://ibs.ru/'", () ->
                open("https://ibs.ru/"));

        step("click on Accept cookies button", () -> {
            $(".cookie.cookie__show").$(byText("Принимаю условия")).click();
        });

        step("click on ENG button", () -> {
            $(".header__lang.lang").$(byText("ENG")).click();
        });

        step("click on Technology Partners", () -> {
            $(".aside-navigation__list").$(byText("Technology Partners")).click();
        });

        step("click on SHOW", () -> {
            $("#ajax_load").click();
        });

        step("page should have modal ROBIN Partner", () -> {
            $(".vendors-project-list.ajax_result").shouldHave(Condition.text("ROBIN"));
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://ibs.ru/'", () ->
                open("https://ibs.ru/"));

        step("Page title should have text 'IBS — ведущая российская IT-сервисная компания'", () -> {
            String expectedTitle = "IBS — ведущая российская IT-сервисная компания";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://ibs.ru/'", () ->
                open("https://ibs.ru/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}